### ISSUE TITLE
Peer invalid

### ISSUE THREAD

**Issue by felixheidecke** [nvoinov/grunt-remove#6]
_Invalid peer_ when trying to install using **grunt@1.0.1**

```
npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-remove" "--save-dev"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-remove@0.1.0 wants grunt@~0.4.1
```

**Comment by rarila** [comment]
@felixheidecke Switching to npm v3 (if possible) would "solve" your problem by turning the error into a warning.

@nvoinov Could you please merge in #5 to solve this? Would be really great! :smiley:

**Comment by nvoinov** [comment]
I'm merge your pull request, thanks

**Comment by rarila** [comment]
@nvoinov Great! Could you please also bump release numbers as one still gets the old version with npm. Thanks in advance!
